# Cream Cheese Cookies

## Ingredients

| Ingredients | Amount (~18 cookies) | Amount (~36 cookies) |
|--- |---|---|
| **Dry** | | |
| Flour | 210 grams | 420 grams |
| Salt | $\frac{1}{2}$ teaspoon | 1 teaspoon |
| Baking powder | $\frac{1}{2}$ teaspoon |1 teaspoon |
| **Wet** | | |
| Butter | 114 grams | 228 grams |
| Cream cheese | 114 grams | 228 grams |
| White sugar | 200 grams | 400 grams |
| Egg | 1 | 2 |
| Vanilla extract | 2 teaspoons | 4 teaspoons |

## Directions

1. Start by browning the butter. Then let the browned butter cool down to room temperature.

2. In a bowl sift the flour, baking powder, and the salt. Then whisk all together.

3. In a separate bowl mix the browned butter and cream cheese at room temperature until well combined before adding the sugar. Mix to create batter.

4. Add the egg at room temperature and the vanilla to the batter and continue mixing.

5. Add the dry mixture to the wet mixture and mix until just combined.

6. Chill for at least an hour, but preferably more or overnight.

7. Roll each dough ball to about 35 grams or to desired size.

8. Bake at $375 ^\circ$ F for about 10 minutes or until the edges are turning golden brown.

9. Dust the cookies with powdered sugar, drizzle with melted white chocolate, or cream cheese frosting.
