---
title: "Double Chocolate Chip Cookies"
format: html
---

## Ingredients

| Ingredients | Amount (single batch) | Amount (double batch) |
|---|---|---|
| **Dry** | | |
| Flour | 120 grams | 240 grams |
| Salt | $\frac{1}{2}$ teaspoon | 1 teaspoon |
| Baking soda | $\frac{1}{2}$ teaspoon | 1 teaspoon |
| *Cacao powder* | 33 grams | 66 grams |
| **Wet** | | |
| Butter | 114 grams | 228 grams |
| White sugar | 66 grams | 132 grams |
| Brown sugar | 110 grams | 220 grams | 
| Egg | 1 | 2 |
| Vanilla extract | 2 teaspoons | 4 teaspoons|
| **Mix-ins** | | |
| Chocolate chips *(semi-sweet of dark)* | 180 grams | 360 grams | 

## Directions

1. Start by browning the butter. Then let the browned butter cool down to room temperature.

2. In a bowl sift and mix the dry ingredients together.

3. In a separate bowl mix the browned butter, brown sugar, and white sugar to create the batter.

4. Add the egg at room temperature and the vanilla to the batter and continue mixing.

5. Add the dry mixture to the wet mixture and mix. Then add the chocolate chips and continue to mix until just combined. Do not overmix the batter. 

6. Chill the dough for a couple hours.

7. If baking from
    - Fresh, 350 for about 10 minutes 
    - Frozen 335-340 for about 17 minutes 
