---
title: "Oatmeal Raisin Cookies"
format: html
---

## Ingredients

| Ingredients | Amount |
 --- | --- |
| **Dry** | | 
| Flour | 120 grams |
| Salt | $\frac{1}{2}$ teaspoon  |
| Baking soda | $\frac{1}{2}$ teaspoon |
| Cinnamon | $\frac{1}{2}$ teaspoon |
| Nutmeg | $\frac{1}{4}$ teaspoon |
| **Wet** | |
| Butter | 114 grams |
| White sugar | 65 grams |
| Brown sugar | 140 grams | 
| Egg | 1 |
| Vanilla extract | 2 teaspoons | 
| **Mix-ins** | |
| Rolled oats | 135 grams |
| Raisins  | 150 grams |
| Nuts (Pecans or Walnuts) | 50-75 grams |

## Directions

1. Start by browning the butter. Then let the browned butter cool down to room temperature.

2. In a bowl sift and mix the dry ingredients together.

3. In a separate bowl mix the browned butter, brown sugar, and white sugar to create the batter.

4. Add the egg at room temperature and the vanilla to the batter and continue mixing.

5. Add the dry mixture to the wet mixture and mix. Then add the oatmeal, raisins, and other mix-ins and continue to mix until just combined. Do not overmix the batter. 

6. Chill the dough for a couple hours.

7. If baking from
    - Fresh, 350 for about 10 minutes 
    - Frozen 335-340 for about 17 minutes